# Use root/example user/password credentials
version: '2.4'

services:
  php:
    links:  #Definir o serviço que precisa de conexão (banco de dados)
      - "db"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:80:80 #Especificar interface de host
    read_only: true
    tmpfs:
      - /tmp
      - /run/apache2
      - /run/lock
    volumes:
      - ./src:/var/www/html/
    cap_drop: #Controlar capacidades
      - all
    cap_add:
      - NET_BIND_SERVICE
    restart: on-failure:5
    cpu_percent: 20 #Restringir CPU
    mem_limit: 10m #Restringir memória
    mem_reservation: 6m
    pids_limit: 100 #Restringir PID
    healthcheck: #Verificar status do container
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt: #Garantir que nao ganhe privilegios
      - no-new-privileges 

  db:
    links:
      - "adminer"
    build:
      context: .
      dockerfile: Dockerfile_db
    #image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    read_only: true
    tmpfs:
    - /tmp
    - /run/mysqld
    volumes:
      - mysql-data:/var/lib/mysql
    cap_drop:
      - all
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: on-failure:5
    cpu_percent: 20
    mem_limit: 380m
    mem_reservation: 360m
    pids_limit: 100
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 1m30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges 
    #  - dbarmor Campo para carregar o perfil apparmor ou selinux


  adminer:
    image: adminer
    ports:
      - 127.0.0.1:8080:8080
    restart: on-failure:5
    cpu_percent: 20
    mem_limit: 10m
    mem_reservation: 6m
    pids_limit: 100
    read_only: true
    tmpfs:
      - /tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges
    

volumes:
  mysql-data:
